name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install
      run: npm install
    - name: build
      run: npm run build -- --prod
      
      
  test:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: install
        run: npm install
      - name: run tests
        run: npm run test -- --watch=false 
